spring:
  application:
    name: GraphQL Project
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    hikari:
      connection-timeout: 2000
      initialization-fail-timeout: 0
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          batch_size: 50
          order_inserts: true
          order_updates: true
  sql:
    init:
      mode: always

graphql:
  spqr:
    gui:
      enabled: true
